#
# This file contains configuration flags to customize your site
#
# Name of your site (displayed in the header)
markdown: kramdown
name: "luowei's blog"
# Short bio or description (displayed in the header)
description: "A blog for sharing my thoughts and experiences"
#private: true # Set to true to disable search engine indexing
#
# Flags below are optional
#

# URL of your avatar or profile pic (you could use your GitHub profile pic),需要外链图片，否则无法显示
avatar: https://img2.imgtp.com/2024/05/09/cchqKxZE.png
# avatar:https://github.com/luowei01/blog/blob/59b54f42b6816850c7fdad2ab379ae0111611e5e/images/blog.png
# 你的favicon（出现在浏览器tab上）图片URL，建议使用较小(64px × 64px)的图片
favicon: https://img2.imgtp.com/2024/05/09/vMetVwXx.ico

# Tabs in header. There are 'Blog', 'About', 'Archive', 'Tags'
# and URL Link(e.g. 'Theme' tab below) tabs. If you don't need one, just delete
# it from the list(Delete '- name: ' and 'url: ', too!)
navigation:
  - name: 首页
    url: /
  - name: 关于
    url: /about
  - name: 归档
    url: /archive
  - name: 标签
    url: /tags
  - name: 全部博客
    url: /book

# Pagination
paginate: 8

excerpt_separator: <!-- more -->

# Includes an icon in the footer for each username you enter
footer-links:
  #weibo: frommidworld #请输入你的微博个性域名 https://www.weibo.com/<thispart>
  behance: # https://www.behance.net/<username>
  dribbble:
  zhihu: 
  email: 1615108374@qq.com
  facebook:
  flickr:
  github: luowei01 
  googleplus: # anything in your profile username that comes after plus.google.com/
  instagram:
  linkedin:
  pinterest:
  rss: # just type anything here for a working RSS icon
  stackoverflow: # your stackoverflow profile, e.g. "users/50476/bart-kiers"
  tumblr: # https://<username>.tumblr.com
  #twitter: frommidworld
  youtube:

# Text under the icons in footer
footer-text: Copyright (c) 2024 luowei

# Enter your Disqus shortname (not your username) to enable commenting on posts
# You can find your shortname on the Settings page of your Disqus account
disqus: # fromendworld

# Gitalk
gitalk:
  clientID: Ov23liBSx6prTneSyci2
  clientSecret: 62bd6e055b9b0ec67adf218b5207348eaca8ecb7
  repo: blog
  owner: luowei01

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
#google_analytics: 

# Your website URL (e.g. http://barryclark.github.io or http://www.barryclark.co)
# Used for Sitemap.xml and your RSS feed
url: https://luowei01.github.io/blog/

# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
# baseurl: /blog

#
# !! You don't need to change any of the configuration flags below !!
#

permalink: /:title/
paginate_path: /page:num/

# The release of Jekyll Now that you're using
version: v1.2.0

# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'

# Set the Sass partials directory, as we're using @imports
sass:
  style: :expanded # You might prefer to minify using :compressed

# Use the following plug-ins
plugins:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem
  - jekyll-paginate

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME

